name: Update README
on:
  schedule:
    - cron: "0 0 * * *" # Run daily at midnight UTC
  workflow_dispatch:
jobs:
  build:
    name: Update this repo's README with recent activity
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v3
      - uses: shahstavan/shahstavan@master
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}