name: Waka Readme

on:
  workflow_dispatch: # for manual workflow trigger
  schedule:
    - cron: "0 0 * * *" # runs at every 12AM UTC

jobs:
  update-readme:
    name: WakaReadme DevMetrics
    runs-on: ubuntu-latest
    steps:
      - uses: athul/waka-readme@master
      - uses: anmol098/waka-readme-stats@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          # following flags are required, only if this is not on
          # profile readme, remove the leading `#` to use them
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          REPOSITORY: <gh_username/gh_username>
          SHOW_TITLE: true
          SHOW_TOTAL: true
          BLOCKS: ⣀⣄⣤⣦⣶⣷⣿
          TIME_RANGE: last_30_days
          SHOW_TIME: true
          SHOW_MASKED_TIME: true
          LANG_COUNT: 10
          SHOW_LINES_OF_CODE: true
          SHOW_TOTAL_CODE_TIME: true
          SHOW_COMMIT: true
          SHOW_DAYS_OF_WEEK: true
          SHOW_LANGUAGE: true
          SHOW_PROJECTS: true
          SHOW_LANGUAGE_PER_REPO: true
          SHOW_SHORT_INFO: true
        
